In [1]:
from sklearn import datasets
import numpy as np
from random import random

#Loading the dataset

In [2]:
iris = datasets.load_iris()

In [ ]:
print(iris['data'].shape)
print(iris)

In [4]:
def add1tofeature(input):
  x = np.zeros((input.shape[0],(input.shape[1])+1))
  for i in range(input.shape[0]):
    x[i]=np.append(input[i],[1])
  return x

In [5]:
data = iris.data
target = iris.target

c1_train=add1tofeature(data[:42,:])
c1_test=add1tofeature(data[42:50,:])
c1_train_target = target[:42]
c1_test_target = target[42:50]

c2_train=add1tofeature(data[50:92,:])
c2_test=add1tofeature(data[92:100,:])
c2_train_target = target[50:92]
c2_test_target = target[92:100]

c3_train=add1tofeature(data[100:142,:])
c3_test=add1tofeature(data[142:150,:])
c3_train_target = target[100:142]
c3_test_target = target[142:150]

print(c1_train.shape,c1_test.shape)
print(c2_train.shape,c2_test.shape)
print(c3_train.shape,c3_test.shape)
print(data.shape)

(42, 5) (8, 5)
(42, 5) (8, 5)
(42, 5) (8, 5)
(150, 4)


# **Built-in LDA**

In [6]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2)
x_r = lda.fit(data,target).transform(data)
y = lda.predict(data)
print(lda.score(data,target)*100)

98.0


In [7]:
class perceptron:
  def __init__(self,input_size,output_size):
    self.weight = np.random.rand(output_size,input_size)

  def activation(self,x):
    return (1/(1+np.exp(-x)))

  def forward(self,input,net): 
    self.output = np.dot(input,self.weight[net])
    self.output = self.activation(self.output)
    return self.output

  def backward(self,input,output,e,error):
    weight = self.weight - e * np.dot(error,input)
    return weight

  def LDA(self,w,input):
    wT = w.transpose()
    return np.dot(wT,input)

In [8]:
def training_data(data,target,size,nets,maxIter,lr):
  for x in range(data.shape[0]):
    for k in range(size):
      for i in range(nets):
        op=perceptron.forward(data[x][k],i)
        delta = np.dot((target[x][k] - op),(1 - op))
        delta  = np.dot(delta,op)
        for j in range(maxIter):
          updatedWeight=perceptron.backward(data[x][k],op,lr,target[x][k])
  return updatedWeight

def testing_data(data,target,weight):
  prediction = np.zeros((data.shape[0],data.shape[1]))
  for i in range(data.shape[0]):
    for j in range(data.shape[1]):
      d = np.zeros(3)
      for k in range(weight.shape[0]):
        d[k]=perceptron.LDA(weight[k],data[i][j])
      print(d)
      index = d.argmax()
      prediction[i][j]=index  
  return prediction

def accuracy(prediction,label):
  counter=0
  error=0
  for i in range(prediction.shape[0]):
    for j in range(prediction.shape[1]):
      if prediction[i][j]==label[i][j]:
        counter+=1
      else:
        error+=1
  return (counter/(label.shape[0]*label.shape[1]))*100

In [9]:
nets = 3
maxIter = 1000
learningRate = 0.001
output=np.zeros(nets)
perceptron = perceptron(c1_train.shape[1],nets)
#training data
data = np.array([c1_train,c2_train,c3_train])
target = np.array([c1_train_target,c2_train_target,c3_train_target])
w=training_data(data,target,data.shape[1],nets,maxIter,learningRate)
print(w)

[[ 0.68360789  0.65477711  0.88794302  0.05431714  0.05696232]
 [ 0.59524737  0.28072254  0.56138102  0.82876933  0.54570513]
 [-0.00630555  0.73319797  0.78712359  0.44671702  0.59078654]]


## **Testing Data**

In [ ]:
test_data = np.array([c1_test,c2_test,c3_test])
target_data = np.array([c1_test_target,c2_test_target,c3_test_target])
prediction = testing_data(test_data,target_data,w)
ac = accuracy(prediction,target_data)
print("The accuracy is " ,ac, "%")